# Generated by Django 4.1 on 2022-08-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
