# Generated by Django 4.1 on 2022-08-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_tags_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
