# Generated by Django 4.1 on 2022-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
