# Generated by Django 4.1 on 2022-08-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_post_code_post_output_reply_code_reply_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='output',
        ),
    ]
