# Generated by Django 4.1 on 2022-08-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_post_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='output',
        ),
    ]
