# Generated by Django 4.1 on 2022-08-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_compiler', '0002_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
