# Generated by Django 4.1 on 2022-08-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_compiler', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
